config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  get '/users', to: 'users#index', as: :all_users
  get '/users/:id', to: 'users#show', as: :show_user
  get '/menus/', to: 'menus#index', as: :all_days
  post '/menus', to: 'menus#create', as: :create_menu
  get '/menus/edit_current', to: 'menus#edit_current', as: :current_menu
  get '/menus/:id', to: 'menus#show', as: :show_menu
  get '/menu_items/autocomplete_menu_item_name', as: :autocomplete_menu_item_name
  delete '/menus/current/menu_items/:id', to: 'menu_items#destroy', as: :delete_menu_item
  post '/menus/current', to: 'menus#add_last_week_items', as: :add_last_week_items
  post '/menus/current/menu_items', to: 'menu_items#create', as: :create_menu_item
  get '/user_lunches/new', to: 'user_lunches#new', as: :new_user_lunch
  post '/user_lunches', to: 'user_lunches#create', as: :create_user_lunch

  namespace :api do
    namespace :v1 do
      get '/user_orders', to: 'user_orders#index'
    end
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items, dependent: :destroy
  accepts_nested_attributes_for :menu_items

  validates :date, presence: true

  paginates_per 20

  def day_menu_dishes_hash
    if menu_items.empty?
      menus = nil
    else
      menus = {}
      MenuItem::CATEGORIES.each do |course|
        menus[course] = menu_items.where(category: course)
      end
    end
    menus
  end

  def day_lunches
    sql = format("Select users.user_name, menu_items.name, menu_items.category, menu_items.price
                  FROM (select user_id, dish_id, created_at FROM user_lunches WHERE created_at::date = '%s') as first
                  JOIN (select id, user_name from users) as users ON first.user_id = users.id
                  JOIN (select id, name, price, category from menu_items) as menu_items ON first.dish_id = menu_items.id
                  ORDER BY first.created_at", date)
    ActiveRecord::Base.connection.execute(sql)
  end

  def day_lunches_cost
    sql = format("Select SUM(menu_items.price) as total FROM
                  (SELECT dish_id FROM user_lunches WHERE created_at::date = '%s') as lunches
                  JOIN (select id, price FROM menu_items) as menu_items ON lunches.dish_id = menu_items.id", date)
    ActiveRecord::Base.connection.execute(sql)[0]['total']
  end

  def add_last_week_items
    last_weekday_menu = Menu.find_by(date: (Time.zone.today - 7))
    if last_weekday_menu&.menu_items
      last_weekday_menu&.menu_items&.each do |item|
        menu_items.create(name: item.name, category: item.category, price: item.price, photo: item.photo)
      end
    end
  end

  def self.all_days
    Menu.select(:id, :date)
  end

  def self.last_days(number = 5)
    Menu.order(date: :desc).limit(number)
  end

  def self.today_menu
    current_menu = Menu.find_by(date: Time.zone.today)
    unless current_menu
      current_menu = Menu.new(date: Time.zone.today)
      current_menu.save
    end
    current_menu
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :admin_only!

  def index
    @all_days = Menu.all_days.order(date: :desc).page params[:page]
  end

  def edit_current
    @day_menu = Menu.today_menu
    @menu_item = @day_menu.menu_items.build
    @existed_menu_items = MenuItem.recent_items
    @dish_categories = MenuItem::CATEGORIES
  end

  def add_last_week_items
    if params[:load_last_week][:load]
      if Menu.today_menu.add_last_week_items
        redirect_to current_menu_path, notice: 'Success'
      else
        redirect_to current_menu_path, alert: 'Empty'
      end
    end
  end

  def show
    @menu = Menu.find(params[:id])
    @dishes_hash = @menu.day_menu_dishes_hash
    @user_lunches = Kaminari.paginate_array(@menu.day_lunches.to_a).page(params[:page]).per(30)
    @lunches_cost = @menu.day_lunches_cost
  end
end

app/views/menus/edit_current.html.erb
<head>
  <script type="text/javascript">
      $(document).ready(function() {
          $(window).keydown(function(event){
              if(event.keyCode === 13) {
                  event.preventDefault();
                  return false;
              }
          });
      });
  </script>
</head>
<h1>Add item to menu</h1>
<%= simple_form_for :load_last_week, url: add_last_week_items_path do |f| %>
  <%= f.input :load, :as => :hidden, :input_html => { value: true }  %>
  <%= f.submit "Add all menu items from last #{Time.zone.today.strftime('%A').downcase}" %>
<% end %>
<h3>Search among recent menu items:</h3>
<%= form_for @existed_menu_items ? @menu_item : @existed_menu_items, url: autocomplete_menu_item_name_path  do |f| %>
  <%= f.autocomplete_field :name, autocomplete_menu_item_name_path, 'data-showNoMatches' => false,
                           update_elements: { name: '#menu_item_new_name', category: '#menu_item_category',
                                              id: '#menu_item_id', price: '#menu_item_price'}%>
<% end %>
<h3>Or create new one:</h3>
<%= simple_form_for(@menu_item,  url: create_menu_item_path, method: :post,
                    html: { class: 'form' }) do |f| %>
  <%= f.input :name, input_html: {id: "menu_item_new_name"} %>
  <%= f.input :category, collection: @dish_categories %>
  <%= f.input :price %>
  <%= f.input :photo %>
  <%= f.button :submit, 'Add menu item' %>
<% end %>
<h1>Today's menu</h1>
<table class="table table-sm">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Category</th>
    <th scope="col">Price</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% if @day_menu.menu_items %>
    <% @day_menu.menu_items.each do |menu_item| %>
      <% unless menu_item.new_record? %>
        <tr>
          <th>
            <%= menu_item.name %>
          </th>
          <th>
            <%= menu_item.category %>
          </th>
          <th>
            <%= menu_item.price %>
          </th>
          <th>
            <%= link_to 'Remove', delete_menu_item_path(menu_item.id), method: :delete %>
          </th>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/menus/index.html.erb
<h1>All days</h1>
<table class="table table-sm">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Day of week</th>
    <th scope="col">Data</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% if @all_days %>
    <% @all_days.each do |day| %>
      <tr>
        <th>
          <%= day.date.strftime('%A') %>
        </th>
        <th>
          <%= day.date.strftime("%d %b %Y") %>
        </th>
        <th>
          <%= link_to 'Open day page', show_menu_path(day.id) %>
        </th>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<%= paginate @all_days %>

app/views/menus/new.html.erb
<p>Create today's menu:</p>
<%= simple_form_for(@menu,  url: create_menu_path, method: :post,
                    html: { class: 'form' }) do |f| %>
  <%= f.button :submit, 'Create!' %>
<% end %>

app/views/menus/show.html.erb
<% if @menu %>
  <div>
    <h2>
      <%= @menu.date.strftime("%A, %d %b %Y") %>
    </h2>
  </div>
  <% if @dishes_hash %>
    <% @dishes_hash.each do |course_name, dishes| %>
        <div class="col-lg-4">
          <h3>
            <%= course_name.to_s.capitalize + ':' %>
          </h3>
          <% dishes.each do |dish| %>
            <div class="row">
              <div class="col">
                <%= dish.name.to_s + ', ' + dish.price.to_s %>
              </div>
            </div>
          <% end %>
        </div>
    <% end %>
  <% else %>
    <div>
      <p>
        This day's menu is empty
      </p>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <% if @lunches_cost %>
        <h3>
          Total cost:
          <%= @lunches_cost %>
        </h3>
      <% end %>
      <h3>Users orders:</h3>
    </div>
    <div class="col-lg-12">
      <% if @user_lunches %>
        <%= paginate @user_lunches %>
        <table class="table table-sm">
          <thead class="thead-dark">
          <tr>
            <th scope="col">Users name</th>
            <th scope="col">Dish</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
          </tr>
          </thead>
          <tbody>
          <% @user_lunches.each do |lunch| %>
            <tr>
              <th>
                <%= lunch['user_name'] %>
              </th>
              <th>
                <%= lunch['name'] %>
              </th>
              <th>
                <%= lunch['category'] %>
              </th>
              <th>
                <%= lunch['price'] %>
              </th>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>

<% else %>
  <span>Still empty...</span>
<% end %>