config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  get '/users', to: 'users#index', as: :all_users
  get '/users/:id', to: 'users#show', as: :show_user
  get '/menus/', to: 'menus#index', as: :all_days
  post '/menus', to: 'menus#create', as: :create_menu
  get '/menus/edit_current', to: 'menus#edit_current', as: :current_menu
  get '/menus/:id', to: 'menus#show', as: :show_menu
  get '/menu_items/autocomplete_menu_item_name', as: :autocomplete_menu_item_name
  delete '/menus/current/menu_items/:id', to: 'menu_items#destroy', as: :delete_menu_item
  post '/menus/current', to: 'menus#add_last_week_items', as: :add_last_week_items
  post '/menus/current/menu_items', to: 'menu_items#create', as: :create_menu_item
  get '/user_lunches/new', to: 'user_lunches#new', as: :new_user_lunch
  post '/user_lunches', to: 'user_lunches#create', as: :create_user_lunch

  namespace :api do
    namespace :v1 do
      get '/user_orders', to: 'user_orders#index'
    end
  end
end

app/models/user_lunch.rb
class UserLunch < ApplicationRecord
  belongs_to :user
  belongs_to :menu_item, foreign_key: 'dish_id', inverse_of: :user_lunches

  validates :menu_item, :user, presence: true
end

app/controllers/user_lunches_controller.rb
class UserLunchesController < ApplicationController
  before_action :user_already_make_order

  def new
    @user_lunch = []
    MenuItem::CATEGORIES.size.times do
      @user_lunch << UserLunch.new
    end
    @today_menu_courses = Menu.today_menu.day_menu_dishes_hash
    @dish_categories = MenuItem::CATEGORIES
  end

  def create
    permitted_params = user_lunch_params
    ActiveRecord::Base.transaction do
      MenuItem::CATEGORIES.each do |category|
        if permitted_params[category]
          @user_lunch = current_user.user_lunches.build(permitted_params[category])
          @user_lunch.save!
        else
          raise ActiveRecord::Rollback
        end
      end
    end
  rescue StandardError
    redirect_to new_user_lunch_path, alert: 'Order creation failed'
  else
    redirect_to '/', notice: 'Order created successfully'
  end

  private

  def user_lunch_params
    params.require(:user_lunch).permit(first_dish: [:dish_id], main_dish: [:dish_id], drink: [:dish_id])
  end

  def user_already_make_order
    redirect_to '/', alert: 'Today you have already made an order.' unless
        UserLunch.where('created_at::date = ?', Menu.today_menu.date).where(user: current_user.id).empty?
  end
end

app/views/user_lunches/new.html.erb
<% if @today_menu_courses %>
  <h2>Make your order for today</h2>
  <%= simple_form_for(@user_lunch, url: create_user_lunch_path, method: :post) do |f| %>
    <% @user_lunch.each_with_index do |category, index| %>
      <%= simple_fields_for category do |c| %>
        <%= c.input :menu_item, collection: @today_menu_courses[@dish_categories[index]],
                    label: @dish_categories[index].humanize,
                    input_html: { name: 'user_lunch[' + @dish_categories[index] + '][dish_id]' }, as: :radio_buttons %>
      <% end %>
    <% end %>
    <%= f.button :submit, 'Submit' %>
  <% end %>
<% else %>
  <p>
    This day's menu is still empty. Please wait while the administrator will add today's dishes.
  </p>
<% end %>