config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  get '/users', to: 'users#index', as: :all_users
  get '/users/:id', to: 'users#show', as: :show_user
  get '/menus/', to: 'menus#index', as: :all_days
  post '/menus', to: 'menus#create', as: :create_menu
  get '/menus/edit_current', to: 'menus#edit_current', as: :current_menu
  get '/menus/:id', to: 'menus#show', as: :show_menu
  get '/menu_items/autocomplete_menu_item_name', as: :autocomplete_menu_item_name
  delete '/menus/current/menu_items/:id', to: 'menu_items#destroy', as: :delete_menu_item
  post '/menus/current', to: 'menus#add_last_week_items', as: :add_last_week_items
  post '/menus/current/menu_items', to: 'menu_items#create', as: :create_menu_item
  get '/user_lunches/new', to: 'user_lunches#new', as: :new_user_lunch
  post '/user_lunches', to: 'user_lunches#create', as: :create_user_lunch

  namespace :api do
    namespace :v1 do
      get '/user_orders', to: 'user_orders#index'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunch Ordering</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">Lunch Ordering</a>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Dashboard', root_path %>
            </li>
            <li class="nav-item">
              <%= link_to 'Make lunch order', new_user_lunch_path %>
            </li>
            <% if current_user.is_admin %>
              <p class="navbar-text">Admin section: </p>
              <li class="nav-item">
                <%= link_to 'All users', all_users_path%>
              </li>
              <li class="nav-item">
                <%= link_to 'Days', all_days_path%>
              </li>
              <li class="nav-item">
                <%= link_to "Today's menu editing", current_menu_path%>
              </li>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.user_name, show_user_path(current_user.id)%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: 'nav-link'  %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% elsif flash[:alert]%>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>